version: "3"
services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    volumes:
      - "./data:/data"
    env_file: "./server/.env"
    environment:
      DATA_FOLDER: /data
      APP_DATA_FOLDER: /appData
      APP_SCRIPTS: /appScripts
      INPUT_FOLDER: /data/input
      OUTPUT_FOLDER: /data/output
      APP_PORT: 3001
    ports:
      - "3001:3001"

  frontend:
    build:
      context: "."
      dockerfile: "./docker/frontend.dockerfile"
      args:
        APP_PATH: /ezqtl
    env_file: "./server/.env"
    environment:
      API_BASE_URL: http://backend:3001
      APP_PATH: /ezqtl
    ports:
      - "3000:80"
